name: Pull Request Verification

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  PR-Verification:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # repo checkout

      # Install Rust Nightly Toolchain, with Clippy & Rustfmt
      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      
      # Required by dependency 'csgoproto'
      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: lint
        run: cargo clippy -- -D warnings
      
      - name: fmt-check
        run: cargo fmt --check
